name: Label sponsors
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
jobs:
  build:
    name: is-sponsor-label
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/is-sponsor-label-action@8eaf3d7c012108c636be08283a1f7cff55651094
        with:
          label: Sponsor 💖
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
